# Generated by Django 4.2.3 on 2023-08-12 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_collection_id_remove_collection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='col_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='api.collection'),
        ),
        migrations.AddField(
            model_name='story',
            name='st_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
