# Generated by Django 4.2.3 on 2023-08-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_collection_user_id_story_col_id_story_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='col_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='st_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
