# Generated by Django 4.2.3 on 2023-08-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_collection_col_id_alter_story_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='col_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='api.collection'),
        ),
    ]
