# Generated by Django 4.2.3 on 2023-08-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_story_st_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='col_id',
            new_name='collection',
        ),
    ]
