# Generated by Django 4.2.3 on 2023-08-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_col_id_story_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
    ]
