# Generated by Django 4.2.3 on 2023-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_collection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user',
            new_name='user_id',
        ),
    ]
