# Generated by Django 4.2.3 on 2023-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_collection_story_col_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='col_id',
            new_name='collection',
        ),
    ]
