# Generated by Django 4.2.3 on 2023-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_collection_user_alter_story_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='stories',
            field=models.TextField(default=''),
        ),
    ]
