# Generated by Django 4.2.3 on 2023-08-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_collection_stories_alter_collection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='generated_context',
            field=models.TextField(default=''),
        ),
    ]
